name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What is the bug?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      required: true

  - type: input
    attributes:
      label: Environment
      placeholder: Browser / OS / Node version
