name: 🧹 Chore
description: Maintenance or non-feature task
title: "[CHORE] "
labels: ["chore"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the maintenance task
    validations:
      required: true

  - type: textarea
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Task completed
        - [ ] No behavior changes
